### ISSUE TITLE
Unable to export all metrics as custom_metric_dict is being reset everytime we loop

### ISSUE THREAD

**Issue by mohitrajain** [so1n/graphite_exporter#4]
Python version: 3.7

We are [reseting](https://github.com/so1n/graphite_exporter/blob/b22e6cf7a8309d6de5d955c9a672b0ecebac2c08/graphite_exporter/collector.py#L136) the dictionary custom_metric_dict in the middle of the for [loop](https://github.com/so1n/graphite_exporter/blob/b22e6cf7a8309d6de5d955c9a672b0ecebac2c08/graphite_exporter/collector.py#L128), it's causing only the last metric from series to be published. Easy fix would be to move the reset in get_metric before for loop.

**Comment by so1n** [comment]
Thanks for you issue, I will merge pr after adding test cases over the weekend
